const Legal = () => {
  return (
    <div className="max-w-3xl mx-auto p-6 text-left">
      <h1 className="text-4xl font-bold mb-6">Terms of Use, Legal and Privacy Information</h1>

      {/* Section 1 */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">1. Terms of Use</h2>
      <h3 className="text-xl font-semibold mb-2">Information Purpose:</h3>
      <p className="mb-4">
        SleepSage provides information and recommendations related to over-the-counter sleep
        supplements. This information is for educational and informational purposes only and is not
        intended as a substitute for professional medical advice, diagnosis, or treatment. Users
        should always consult with a qualified healthcare provider before starting any new
        supplement or making changes to their existing healthcare regimen.
      </p>

      <h3 className="text-xl font-semibold mb-2">No Medical Advice:</h3>
      <p className="mb-4">
        SleepSage explicitly states that it does not provide medical advice. The recommendations
        generated by the platform are based on user-provided information and available research, but
        they should not be interpreted as a medical opinion.
      </p>

      <h3 className="text-xl font-semibold mb-2">User Responsibility:</h3>
      <p className="mb-4">
        Users are solely responsible for evaluating the accuracy, completeness, and usefulness of
        any information or recommendations provided by SleepSage. Users assume all risks associated
        with the use of any recommended supplements.
      </p>

      <h3 className="text-xl font-semibold mb-2">Limitations of Liability:</h3>
      <p className="mb-4">
        SleepSage and its team shall not be liable for any direct, indirect, incidental,
        consequential, or punitive damages arising from the use of the platform or reliance on any
        information provided. SleepSage is not responsible for any interactions that the user may
        have with 3rd party affiliate websites.
      </p>

      <h3 className="text-xl font-semibold mb-2">Platform Changes:</h3>
      <p className="mb-4">
        SleepSage reserves the right to modify, suspend, or discontinue the platform or any part
        thereof at any time without notice.
      </p>

      <h3 className="text-xl font-semibold mb-2">Affiliate Links:</h3>
      <p className="mb-4">
        SleepSage may contain affiliate links to third-party products. SleepSage may receive
        compensation for purchases made through these links.
      </p>

      {/* Section 2 */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">2. Privacy Policy</h2>
      <h3 className="text-xl font-semibold mb-2">Information Collection:</h3>
      <p className="mb-4">
        SleepSage collects user-provided information through questionnaires and other forms to
        generate personalized supplement recommendations. We optionally collect email addresses to
        enable features such as saving recommendations and returning to the tool. We may collect
        non-personal information, such as website usage data through Google Analytics 4 (GA4), for
        analytics purposes.
      </p>

      <h3 className="text-xl font-semibold mb-2">Email Usage:</h3>
      <p className="mb-4">
        We may use email addresses for notifications and newsletters, sent no more than
        approximately once every three months. Users can unsubscribe from email communications at
        any time.
      </p>

      <h3 className="text-xl font-semibold mb-2">Data Storage and Security:</h3>
      <p className="mb-4">
        Email addresses are stored on our servers (AWS) and will be encrypted when stored. We take
        reasonable measures to protect user data from unauthorized access, use, or disclosure.
        However, no method of transmission over the internet or electronic storage is 100% secure,
        and we cannot guarantee absolute security.
      </p>

      <h3 className="text-xl font-semibold mb-2">Data Sharing:</h3>
      <p className="mb-4">
        SleepSage will not sell or rent user-provided personal information to third parties. We may
        share email addresses with third parties only with the user's specific and limited consent.
        For example, users may grant permission to be contacted by a sleep therapy company. We may
        share information with trusted third-party service providers who assist us in operating our
        platform, conducting our business, or serving our users, so long as those parties agree to
        keep this information confidential. We may also share information if required by law.
      </p>

      <h3 className="text-xl font-semibold mb-2">User Control and Access:</h3>
      <p className="mb-4">
        Users cannot directly modify their email addresses. Users can request data deletion by
        contacting us through the provided contact information on our website. We will process data
        deletion requests in accordance with applicable laws.
      </p>

      <h3 className="text-xl font-semibold mb-2">Cookies and Tracking:</h3>
      <p className="mb-4">
        We use Google Analytics 4 (GA4) for website analytics, which may use cookies.
      </p>

      <h3 className="text-xl font-semibold mb-2">Age Restrictions:</h3>
      <p className="mb-4">There are no age restrictions currently in place.</p>

      {/* Section 3 */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        3. Changes to Legal and Privacy Information
      </h2>
      <p className="mb-4">
        SleepSage reserves the right to update or modify these legal and privacy terms at any time.
        Users are encouraged to review these terms periodically for any changes.
      </p>

      {/* Section 4 */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">4. Contact Information</h2>
      <p className="mb-4">
        For questions or concerns about these legal and privacy terms, please contact us through the
        provided contact information on our website.
      </p>
    </div>
  );
};

export { Legal };
